OPTIONS(ROWS=10000,DIRECT=True)
LOAD DATA
CHARACTERSET ZHS16GBK
INFILE "/zsoft/yxsp/file/res/INT_PTY_INFO_MANAGER_20170807.dat"
INTO TABLE yxsp_INT_PTY_INFO_MANAGER
TRUNCATE
FIELDS TERMINATED BY ','
TRAILING NULLCOLS
(
	ODS_DATE,
	MANAGER_ID,
	MANAGER_NAME,
	CUST_ID,
	CHANNEL_ID,
	CITY_ID,
	COUNTY_ID,
	MANAGER_TYPE,
	MANAGER_LEVEL,
	REG_NBR,
	CREATE_DATE DATE "YYYY-MM-DD HH24:MI:SS",
	STATUS_ID,
	BIND_NUMBER,
	STAFF_ID,
	ETL_TIME DATE "YYYY-MM-DD HH24:MI:SS",
	SALE_TYPE,
	SALE_TYPE_NAME
)
